GoProShop/Controllers/OrderedProductController.cs
using AutoMapper;
using GoProShop.BLL.DTO;
using GoProShop.BLL.Services.Interfaces;
using GoProShop.ViewModels;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace GoProShop.Controllers
{
    [Authorize(Roles = "admin")]
    public class OrderedProductController : Controller
    {
        private readonly IOrderedProductService _orderedProductService;
        private readonly IResponseService _responseService;

        public OrderedProductController(
           IOrderedProductService orderedProductService,
           IResponseService responseService)
        {
            _orderedProductService = orderedProductService ?? throw new ArgumentNullException(nameof(orderedProductService));
            _responseService = responseService ?? throw new ArgumentNullException(nameof(responseService));
        }

        public async Task<ActionResult> UpdateOrderedProducts(IEnumerable<int> productsId, int orderId)
        {
            await _orderedProductService.AddOrderedProductsAsync(productsId, orderId);

            return Json(_responseService.Create(true, string.Empty, Url.Action("GetOrderedProducts", new { id = orderId })), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetOrderedProducts(int id)
        {
            var orderedProducts = _orderedProductService.GetAll(x => x.ProductId == id);
            var orderedProductsVm = Mapper.Map<IEnumerable<OrderedProductDTO>, IEnumerable<OrderedProductVM>>(orderedProducts);

            return PartialView("_OrderedProducts", orderedProductsVm);
        }

        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Delete(int orderedProductId)
        {
            var response = Mapper.Map<ResponseVM>(await _orderedProductService.DeleteAsync(orderedProductId, "Delete"));
            return Json(response, JsonRequestBehavior.AllowGet);
        }
    }
}

GoProShop/Views/OrderedProduct/_OrderedProducts.cshtml
@model IEnumerable<GoProShop.ViewModels.OrderedProductVM>
<div class="row" style="margin-top: 20px;">
    <div class="col-md-12">
        <table class="table table-responsive table-striped">
            <thead>
                <tr>
                    <td class="text-center">Фото</td>
                    <td>Название</td>
                    <td>Количество</td>
                    <td>Цена</td>
                    <td class="text-center">Удалить</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var orderedProduct in Model)
            {
                    @Html.HiddenFor(model => orderedProduct)
                    <tr>
                        <td class="text-center">
                            @if (orderedProduct.Product.MimeType == null)
                            {
                                <img height="30" width="35" src="~/Content/Images/No_Image_Available.png" alt="Фото" />
                            }
                            else
                            {
                                <img height="30" width="35" src="@Url.Action("GetImage", "Product", new { productId = orderedProduct.Product.Id })" alt="Фото">
                            }
                        </td>
                        <td>@orderedProduct.Product.Name</td>
                        <td>@orderedProduct.Quantity шт.</td>
                        <td>@orderedProduct.Product.Price руб.</td>
                        <td class="text-center"><a class="btn btn-default btn-sm" href="@Url.Action("Delete", "OrderedProduct", new { orderedProductId = orderedProduct.Id })" onclick="deleteEntityFromTable(event,this)"><i class="fa fa-trash-o text-danger"></i></a></td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr style="border-top: 1px solid #ddd">
                    <td style="border: none" colspan="4" class="text-right">Итого:</td>
                    <th style="border: none" class="text-center">@Model.Sum(x => x.Price)</th>
                </tr>
                <tr>
                    <td style="border: none" colspan="4" class="text-right">Cумма скидки:</td>
                    <th style="border: none"  class="text-center">0</th>
                </tr>
                <tr>
                    <td style="border: none" colspan="4" class="text-right">Cумма с учетом скидки:</td>
                    <th style="border: none" class="text-center">@Model.Sum(x => x.Price)</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

<script>
    $(function () {
        var element = $('#product-select');

        $(".chosen-select").chosen({
            search_contains: true, // kwd can be anywhere
            max_selected_options: 10,
            max_shown_results: 300, // show only 5 suggestions at a time
            width: 400,
            no_results_text: "Oops, nothing found!"
        });

        $.when(getChosenOptions()).done(function () {
            $(".chosen-select").trigger("chosen:updated");
        });

        function getChosenOptions() {
            return $.get('/Chosen/GetChosenProducts/', function (data) {
                $.each(data, function (index, item) {
                    element.append($('<option></option>')
                        .val(item.Id)
                        .text(item.Name));
                });
            });
        }
    });
</script>