GoProShop/ViewModels/Feedback/BaseFeedbackVM.cs
using GoProShop.Enums;
using System;
using System.ComponentModel.DataAnnotations;

namespace GoProShop.ViewModels
{
    public class BaseFeedbackVM : IdProvider
    {
        [Display(Name = "Имя")]
        [Required(ErrorMessage = "Поле имя является обязательным")]
        [StringLength(40, MinimumLength = 3, ErrorMessage = "Длина поля имя должна быть не меньше 3 и не больше 40 символов")]
        public string Name { get; set; }

        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Значение поля email не соответсвует формату адреса электронной почты")]
        [Required(ErrorMessage = "Поле email является обязательным")]
        public string Email { get; set; }

        [Display(Name = "Дата")]
        public DateTime Date { get; set; } = DateTime.Now;

        [Display(Name = "Статус")]
        public FeedbackStatus Status { get; set; }

        [ScaffoldColumn(false)]
        public bool IsViewed { get; set; }

        [Required(ErrorMessage = "Оценка работы является обязательным")]
        [Range(1,5, ErrorMessage = "Ретинг работы должен быть в диапазоне от 1 до 5")]
        public int Rating { get; set; }

        [ScaffoldColumn(false)]
        public int? ProductId { get; set; }

        [Display(Name = "Сообщение")]
        [Required(ErrorMessage = "Поле сообщение является обязательным")]
        [StringLength(250, MinimumLength = 3, ErrorMessage = "Длина поля сообщение должна быть не меньше 3 и не больше 250 символов")]
        public string Message { get; set; }
    }
}

GoProShop/ViewModels/Feedback/FeedbackVM.cs
using GoProShop.Enums;
using System;
using System.ComponentModel.DataAnnotations;

namespace GoProShop.ViewModels
{
    public class FeedbackVM : BaseFeedbackVM
    {
        [Required(ErrorMessage = "Поле фамилия является обязательным")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Длина поля фамилия должна быть не меньше 3 и не больше 20 символов")]
        [ScaffoldColumn(false)]
        public string SurName { get; set; }
    }
}

GoProShop/Controllers/AdminController.cs
using AutoMapper;
using GoProShop.BLL.Services.Interfaces;
using GoProShop.ViewModels;
using System;
using System.Web.Mvc;

namespace GoProShop.Controllers
{
    public class AdminController : Controller
    {
        private readonly IAdminService _adminService;

        public AdminController(IAdminService adminService)
        {
            _adminService = adminService ?? throw new ArgumentNullException(nameof(adminService));
        }

        public ActionResult Index()
        {
            var adminPageDTO = _adminService.Build();
            var adminPageVM = Mapper.Map<AdminPageVM>(adminPageDTO);

            return View(adminPageVM);
        }

        public ActionResult Orders() => PartialView();

        public ActionResult Price() => PartialView();

        public ActionResult Stores() => View();

        public ActionResult Feedbacks() => PartialView("_Feedbacks");
    }
}

GoProShop/Controllers/FeedbackController.cs
using AutoMapper;
using GoProShop.BLL.DTO;
using GoProShop.BLL.Services.Interfaces;
using GoProShop.ViewModels;
using PagedList;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace GoProShop.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly IFeedbackService _feedbackService;
        private readonly IResponseService _responseService;

        public FeedbackController(IFeedbackService feedbackService,
            IResponseService responseService)
        {
            _feedbackService = feedbackService ?? throw new ArgumentNullException(nameof(feedbackService));
            _responseService = responseService ?? throw new ArgumentNullException(nameof(responseService));
        }

        public ActionResult Create(int? productId)
        {
            if (productId.HasValue)
            {
                ViewBag.ProductId = productId.Value;
            }

            return PartialView("_Create");
        }


        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ActionResult> Create(FeedbackVM feedbackVM)
        {
           await Task.Delay(700);
            if (!ModelState.IsValid)
            {
                if (feedbackVM.ProductId.HasValue)
                {
                    ViewBag.ProductId = feedbackVM.ProductId;
                }

                return PartialView("_Create", feedbackVM);
            }
               
            await _feedbackService.CreateAsync(Mapper.Map<FeedbackDTO>(feedbackVM));
            var response = Mapper.Map<ResponseVM>(_responseService.Create(true,
                "Cпасибо за ваш отзыв. Нам важно ваше мнение!"));

            return Json(response);
        }

        public ActionResult GetProductFeedbacks(int productId, int page = 1)
        {

            var feedbacksDTO = _feedbackService.GetProductFeedbacks(productId);
            var feedbacksVM = Mapper.Map<IEnumerable<FeedbackDTO>, IEnumerable<BaseFeedbackVM>>(feedbacksDTO);

            ViewBag.ProductId = productId;
            return PartialView("_ProductFeedbacks", feedbacksVM);
        }

        public ActionResult GetHomeFeedbacks()
        {
            var feedbacksDTO = _feedbackService.GetHomeFeedbacks();
            var feedbacksVM = Mapper.Map<IEnumerable<FeedbackDTO>, IEnumerable<FeedbackVM>>(feedbacksDTO);

            return PartialView("_HomeFeedbacks", feedbacksVM);
        }

        [Authorize(Roles = "admin")]
        public ActionResult GetAdminFeedbacks(int page = 1)
        {
            var feedbacksDTO = _feedbackService.GetFeedbacks();
            var feedbacksVM = Mapper.Map<IEnumerable<FeedbackDTO>, IEnumerable<FeedbackVM>>(feedbacksDTO);

            return PartialView("_AdminFeedbacks", feedbacksVM.ToPagedList(page,7));
        }

        [Authorize(Roles = "admin")]
        public async Task<ActionResult> View(int id)
        {
            var pendingFeedbackCount = await _feedbackService.ViewFeedback(id);

            return Json(new { Count = pendingFeedbackCount }, JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Edit(int id)
        {
            var feedbackDTO = await _feedbackService.GetAsync(id);

            if (feedbackDTO == null)
                return Json(_responseService.Create(false, "Отзыва по вашему запросу не существует"));

            var feedbackVM = Mapper.Map<BaseFeedbackVM>(feedbackDTO);
            return PartialView("_Edit", feedbackVM);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Edit(BaseFeedbackVM feedback)
        {
            if (!ModelState.IsValid)
                return PartialView("_Edit", feedback);

            var response = await _feedbackService.UpdateAsync(Mapper.Map<FeedbackDTO>(feedback), "Отзыв");

            return Json(response);
        }

        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Delete(int id)
        {
            var response = Mapper.Map<ResponseVM>(await _feedbackService.DeleteAsync(id, "Отзыв"));
            return Json(response, JsonRequestBehavior.AllowGet);
        }
    }
}

GoProShop/Controllers/OrderController.cs
using AutoMapper;
using GoProShop.BLL.DTO;
using GoProShop.BLL.Services.Interfaces;
using GoProShop.ViewModels;
using PagedList;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace GoProShop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IEmailService _emailService;
        private readonly IResponseService _responseService;

        public OrderController(
            IOrderService orderService,
            IEmailService emailService,
            IResponseService responseService)
        {
            _orderService = orderService ?? throw new ArgumentNullException(nameof(orderService));
            _emailService = emailService ?? throw new ArgumentNullException(nameof(emailService));
            _responseService = responseService ?? throw new ArgumentNullException(nameof(responseService));
        }

        [Authorize(Roles = "admin")]
        public ActionResult GetAdminOrders(int page = 1)
        {
            var ordersDTO = _orderService.GetOrders();
            var ordersVM = Mapper.Map<IEnumerable<OrderDTO>, IEnumerable<OrderVM>>(ordersDTO);

            return PartialView("_AdminOrders", ordersVM.ToPagedList(page, 10));
        }

        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        public async Task<ActionResult> SuccessOrder(int id)
        {
            var orderDTO = await _orderService.GetAsync(id);
            var orderVM = Mapper.Map<OrderVM>(orderDTO);

            return View("~/Views/Order/SuccessOrder.cshtml", orderVM);
        }

        [Authorize(Roles = "admin")]
        public async Task<ActionResult> View(int id)
        {
            var pendingFeedbackCount = await _orderService.ViewOrder(id);

            return Json(new { Count = pendingFeedbackCount }, JsonRequestBehavior.AllowGet);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ActionResult> Create(OrderVM model)
        {
            if (!ModelState.IsValid)
            {
                Thread.Sleep(400);
                return PartialView("_Create", model);
            }

            var session = Session["Cart"] as Cart;
            var orderId = await _orderService.CreateAsync(Mapper.Map<OrderDTO>(model),
                Mapper.Map<IEnumerable<CartItem>, IEnumerable<CartItemDTO>>(session.CartItems));
            session.Clear();

            await _emailService.SendSuccessOrderEmail(orderId);

            return Json(_responseService.Create(true, string.Empty, Url.Action("SuccessOrder", "Order", new { id = orderId })));
        }

        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Edit(int id)
        {
            var orderDto = await _orderService.GetAsync(id);
            return PartialView("_Edit", Mapper.Map<OrderVM>(orderDto));
        }

        [Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(OrderVM model)
        {
            if (!ModelState.IsValid)
            {
                return PartialView("_Edit", model);
            }

            var result = await _orderService.UpdateAsync(Mapper.Map<OrderDTO>(model));

            return Json(result);
        }

        [Authorize(Roles = "admin")]
        public async Task<ActionResult> Delete(int id)
        {
            var response = Mapper.Map<ResponseVM>(await _orderService.DeleteAsync(id, "Заказ"));
            return Json(response, JsonRequestBehavior.AllowGet);
        }
    }
}

GoProShop/Views/Admin/Index.cshtml
@model GoProShop.ViewModels.AdminPageVM

<div class="container-admin">
    <div class="container">
        <ul class="nav nav-tabs">
            <li class="active">
                <a class="ajax-get-link" href="@Url.Action("Orders", "Admin")" data-element-to-update="#adminContent">
                    <i class="fa fa-list-alt admin-tab-icon"></i>Заказы
                    <span class="badge badge-admin-tab" id="new-orders-count">@Model.NewOrdersCount</span>
                </a>
            </li>
            <li>
                <a class="ajax-get-link" href="@Url.Action("Price", "Admin")" data-element-to-update="#adminContent">
                    <i class="fa fa-table admin-tab-icon"></i>Прайс
                </a>
            </li>
            <li>
                <a data-toggle="tab" href="#menu2">
                    <i class="fa fa-tasks admin-tab-icon"></i>Склады
                </a>
            </li>
            <li>
                <a class="ajax-get-link" href="@Url.Action("Feedbacks","Admin")" data-element-to-update="#adminContent">
                    <i class="fa fa-envelope-square admin-tab-icon"></i>Отзывы
                    <span class="badge badge-admin-tab" id="new-feedbacks-count">@Model.NewFeedbacksCount</span>
                </a>
            </li>
        </ul>
    </div>
</div>

<div class="container">
    <div id="adminContent">
        @Html.Action("Orders", "Admin")
    </div>
</div>

GoProShop/Views/Admin/Orders.cshtml
<div class="admin-content-box">
    <div class="admin-content-box__heading">
        <div class="heading-wrapper">
            <p>Заказы</p>
        </div>
    </div>
    <div class="admin-content-box__body">
        <div class="row">
            <div class="col-md-12">
                <div class="table-notification-message">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div id="admin-orders">
                    @Html.Action("GetAdminOrders", "Order")
                </div>
            </div>
        </div>
    </div>
</div>

GoProShop/Views/Admin/Price.cshtml
<div class="col-md-3" style="padding-left: 0;">
    @Html.Action("AdminSideMenu", "ProductGroup")
</div>
<div class="col-md-9" style="padding-right: 0;">
    <div class="panel panel-default">
        <div class="panel-heading"><strong>Товары</strong></div>
        <div class="panel-body" style="padding: 0 14px; font-size: 13px">
            <div id="products">
               @Html.Action("SubGroupAdminProducts", "Product")
            </div>
        </div>
    </div>
</div>

GoProShop/Views/Admin/Stores.cshtml
@{
    ViewBag.Title = "Stores";
}

<h2>Stores</h2>

GoProShop/Views/Admin/_Feedbacks.cshtml
<div class="admin-content-box">
    <div class="admin-content-box__heading">
        <div class="heading-wrapper ">
            <div class="row">
                <div class="col-md-12">
                    <p>Отзывы</p>
                </div>
            </div>
        </div>
    </div>
    <div class="admin-content-box__body">
        <div class="row">
            <div class="col-md-12">
                <div class="table-notification-message">
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-12">
                <div id="admin-feedbacks">
                    @Html.Action("GetAdminFeedbacks", "Feedback")
                </div>
            </div>
        </div>
    </div>
</div>